### PR TITLE
Prevent client to rerender page over SSR error - fixes #710

### LINKED ISSUE #710: Exception in preload leads to flash of content
### Steps to reproduce

```
npx degit sveltejs/sapper-template#webpack my-app
```

create `src/routes/test.svelte`:

```html
<script context="module">
export async function preload(page, session) {
	await this.fetch('http://nosuchhost')
}
</script>

<script>
export let user
</script>

<div>user = {user}</div>
```

### Actual result

Server-side generated HTML contains error message:

```html
<h1 class="svelte-8od9u6">500</h1>

	<p class="svelte-8od9u6">request to http://nosuchhost/ failed, reason: getaddrinfo ENOTFOUND nosuchhost nosuchhost:80</p>

	<pre>FetchError: request to http://nosuchhost/ failed, reason: getaddrinfo ENOTFOUND nosuchhost nosuchhost:80
    at ClientRequest.eval (webpack:///./src/node_modules/@sapper/server.mjs?:1955:11)
    at ClientRequest.emit (events.js:182:13)
    at Socket.socketErrorListener (_http_client.js:391:9)
    at Socket.emit (events.js:182:13)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)</pre>
```

It is displayed for a moment in the browser, but then replaced with `user = undefined`.

In javascript console there is a message: `<Test> was created without expected prop 'user'`

### Expected result

The error message 500 stays there. No errors in javascript console.

### PR DESCRIPTION
**Pull request by rixo**
The preload error was serialized to `null` in preloaded data, so the client thought it got error free preloaded data and rendered the page over the error.

That what's caused the error to disappear (coupled with custom `_layout.svelte`).

But to make things worse, the client doesn't even have data to render at this point.

### CODE REVIEW

**Comment by benmccann** [comment]
Closes https://github.com/sveltejs/sapper/issues/710

File: test/apps/errors/src/routes/preload-reject.svelte [hunk 1]
```diff
@@ -0,0 +1,7 @@
+<script context="module">
+	export function preload() {
```
Comment (benmccann) [inline test/apps/errors/src/routes/preload-reject.svelte:2]: there's a mix of tabs and spaces in this file

File: test/apps/errors/src/routes/preload-reject.svelte [hunk 2]
```diff
@@ -0,0 +1,7 @@
...
+    return Promise.reject(new Error('boom'))
```
Comment (benmccann) [inline test/apps/errors/src/routes/preload-reject.svelte:3]: Convert spaces to tabs

```suggestion
		return Promise.reject(new Error('boom'))
```

**Comment by benmccann** [comment]
Aye aye aye!!!! I'm going a little bit insane (or a lot bit). This is the third separate issue I've hit this week with Sapper swallowing errors :sob: 

Anyway, I've merged this into [my fork](https://github.com/zopost/sapper) and confirmed it works. I'm now getting a stack trace instead of everything looking hunky dory. The stack trace does show the correct line though it's a little tricky to use because it shows the line number in `__sapper__/dev/server/server.js`, which has thousands of lines of unrelated code. It'd be nice if we could use a source map to show the original error location. But that seems like a separate issue.

This would be a great one to merge
