### PR TITLE
Restore hashing of all CSS file names (#1716)

### LINKED ISSUE #1716: No hash appended to client.css filename in v0.29.0
**Describe the bug**
Sapper version 0.29.0 does not add a hash to the `client.css` file. For other css files the hash is added.

**To Reproduce**
```bash
npx degit "sveltejs/sapper-template#rollup" my-app-0.29.0 \
&& cd my-app-0.29.0 \
&& npm i \
&& npm i -D sapper@0.29.0 \
&& npm run build \
&& ls -la __sapper__/build/client/*.css
```
output:
```
__sapper__/build/client/[slug]-5bc8f95f.css
__sapper__/build/client/client.css
__sapper__/build/client/index-39716d32.css
__sapper__/build/client/index-7ed37c94.css
```
In version 0.28.10 everything is ok.

**Expected behavior**
File name client.css with hash like this:
```
__sapper__/build/client/client-abcdefg.css
```

**Severity**
Due to caching of static files, when a new version of the site is released, the user interface is not displayed correctly, users cannot interact with some elements of the site.

**Additional context**
The problem is related to updating rollup-plugin-css-chunks from `1.2.6` to `2.0.2` in sapper `0.29.0` (https://github.com/sveltejs/sapper/pull/1666).
Since version `2.0.0` `rollup-plugin-css-chunks` has a default value of `entryFileNames: '[name].css'`, before that it was ` entryFileNames: '[name]-[hash].css'`

### PR DESCRIPTION
**Pull request by fivemru**
Explicitly use hash in rollup-plugin-css-chunks:
```
chunkFileNames: '[name]-[hash].css',
entryFileNames: '[name]-[hash].css'
```

fix #1716 

### Before submitting the PR, please make sure you do the following
- [x] It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. For large changes, please create an RFC: https://github.com/sveltejs/rfcs
- [x] This message body should clearly illustrate what problems it solves.
- [ ] Ideally, include a test that fails without this PR but passes with it.

### Tests
-  [ ] Run the tests with `npm test` and lint the project with `npm run lint`

### CODE REVIEW

**Comment by benmccann** [comment]
I would expect this to be specified in [Rollup's `output.entryFileNames`](https://rollupjs.org/guide/en/#outputentryfilenames) and then all plugins should use that instead of needing to specify it on a per-plugin basis

**Comment by fivemru** [comment]
> I would expect this to be specified in [Rollup's `output.entryFileNames`](https://rollupjs.org/guide/en/#outputentryfilenames) and then all plugins should use that instead of needing to specify it on a per-plugin basis

The point is that config.client.output () contains the .js extension in the entryFileNames and chunkFileNames fields. https://github.com/sveltejs/sapper/blob/3c01d9300839358e01387c388527f3ec14b0e35b/src/config/rollup.ts#L20
Just replace .js with .css I think it will not be completely predictable behavior.

File: src/core/create_compilers/RollupCompiler.ts [hunk 1]
```diff
@@ -161,7 +161,10 @@ export default class RollupCompiler {
 		const that = this;
 
 		// TODO this is hacky. refactor out into an external rollup plugin
-		(mod.plugins || (mod.plugins = [])).push(css_chunks());
+		(mod.plugins || (mod.plugins = [])).push(css_chunks({
+			chunkFileNames: '[name]-[hash].css',
```
Comment (benmccann) [inline src/core/create_compilers/RollupCompiler.ts:165]: this line shouldn't be necessary since it's the default

**Review by benmccann — COMMENTED** [review]
Ok, makes sense I guess

File: src/core/create_compilers/RollupCompiler.ts (hunk 1 above)
Comment (fivemru) [reply src/core/create_compilers/RollupCompiler.ts]: I agree, deleted it.

**Comment by istarkov** [comment]
Please release.
